### PR TITLE
Set the swift version specific to this pod

### PR DESCRIPTION
**Pull request by shiv19**
This will let this plugin work fine with other plugins that set the swift version in the pod file

### CODE REVIEW

**Comment by arpit2438735** [comment]
@shiv19 Thanks for contributing.There's a PR which specifically remove swift version https://github.com/arpit2438735/nativescript-algolia/pull/21 you can have a look.Main idea is to set it in dev who's is consuming and this plugin which auto take it, rather hardcoding it.

**Comment by shiv19** [comment]
@arpit2438735 
Hi,
The main difference with the changes I have made is that it pins the swift version specifically for this pod
whereas in the lines that were removed in PR#21 I'm not sure if it was doing the same thing.
image

https://cocoapods.org/pods/InstantSearchClient
The InstantSearchClient pod says that the swift version has to be 5 to use that pod.

When I use it in my project without specifying the swift version as 5 specifically for this pod, it doesn't work well with other pods in the project.

As of now, I've added a Podfile to App_Resources/ios/ folder with the block

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'InstantSearchClient'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
end
```

so that just this pod uses swift version 5. This way of pinning swift version is safe, and wouldn't conflict with swift version of other pods.

**Comment by arpit2438735** [comment]
Ahh I see, will merge your change, can you update the package version in the same PR? Thanks

**Review by arpit2438735 — APPROVED** [review]

**Comment by shiv19** [comment]
done :)

**Comment by arpit2438735** [comment]
Thanks.I will bump the version

**Comment by arpit2438735** [comment]
@shiv19 Done 👍

**Pull request merged**
